package it.pioppi.database.entity;

public enum ItemStatus {

    // NOT CHECKED
    WHITE,

    // CHECKED BUT NOT CALCULATED YET
    BLUE,
    // CHECKED AND CALCULATED. NEEDED QUANTITY IS SUFFICIENT
    GREEN,

    // CHECKED AND CALCULATED. NEEDED QUANTITY IS INSUFFICIENT
    RED




}
